name: Rust

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  build:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Update data
        run: python3 ci/update.py
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_KEY }}
