name: Rust

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  build:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: cargo run
        run: cd build && cargo run
